name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563
        with:
          diagnostic-endpoint:
      - uses: DeterminateSystems/magic-nix-cache-action@fc6aaceb40b9845a02b91e059ec147e78d1b4e41
        with:
          diagnostic-endpoint:
      - name: No diff
        run: |
          nix develop -c go mod tidy
          nix develop -c go generate ./...
          nix develop -c go fmt ./...
          git diff --exit-code
      - name: Test
        run: |
          nix develop -c go test ./... -v
      - name: Build state-tool
        run: |
          nix build .#tox4go-state-tool --print-build-logs
